version: '{build}'
skip_tags: true
image: Visual Studio 2022
install:
- cmd: git submodule -q update --init
configuration: Release
platform: x86
build:
  project: compressors\tilecompressordlls.sln
  parallel: true
  verbosity: minimal
after_build:
- cmd: |
    7z a bmp2tilecompressors.zip %APPVEYOR_BUILD_FOLDER%\compressors\Release\*.dll
    7z a bmp2tiledecompressors.zip %APPVEYOR_BUILD_FOLDER%\decompressors\*.asm
before_test:
- cmd: |
    rem Get (some) binaries we need
    appveyor DownloadFile -Url https://github.com/maxim-zhao/sms-build-tools/releases/download/1.0.368/tools.7z -FileName tools.7z
    7z x tools.7z -otools
    rem Add it to the path
    path %cd%\tools;%path%
    rem Copy our DLLs in there
    copy /y %APPVEYOR_BUILD_FOLDER%\compressors\Release\*.dll %cd%\tools
    rem Install dependencies
    py -m pip install matplotlib brokenaxes
test_script:
- py benchmark\benchmark.py compute plot
artifacts:
- path: '*.zip'
- path: '*.svg'
deploy:
- provider: GitHub
  release: Build ${appveyor_build_number}
  auth_token:
    secure: rKUfRHMGs7wVh/SYX9kJ67VqiPlztPwvnh3yjC3C2NX/Wpn9XsZrxIx0BXe9ZztT
  force_update: true